version: '3.9'

services:
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - rabbitmq
    networks:
      host:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    networks:
      host:

networks:
  host:
