server:
  port: '8081'

spring:
  application:
    name: order-worker
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
  jackson:
    time-zone: America/Sao_Paulo
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non-null
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

logging:
  level:
    dev.trodrigues.orderworker.clients.*: DEBUG

mail:
  from: ${MAIL_FROM}

queue:
  name: PURCHASE
  pending: PENDING_PURCHASE

viacep: https://viacep.com.br/ws
